# Generated by Django 3.0.5 on 2020-04-17 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kviz_def',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kviz_nazov', models.CharField(max_length=50)),
                ('kviz_predmet', models.CharField(max_length=100)),
                ('kviz_typ', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Odpoved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odpoved_moja', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Skusanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pokus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokus_uhadol', models.IntegerField(verbose_name=100)),
                ('pokus_neuhadol', models.IntegerField(verbose_name=100)),
                ('pokus_neodpovedal', models.IntegerField(verbose_name=100)),
                ('kviz_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tiaprojekt.Kviz_def')),
                ('odpoved_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tiaprojekt.Odpoved')),
            ],
        ),
        migrations.CreateModel(
            name='Otazka_def',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kviz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiaprojekt.Kviz_def')),
            ],
        ),
        migrations.CreateModel(
            name='Odpoved_def',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odpoved_body', models.IntegerField(verbose_name=100)),
                ('otazka_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiaprojekt.Otazka_def')),
            ],
        ),
        migrations.AddField(
            model_name='odpoved',
            name='otazka_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiaprojekt.Otazka_def'),
        ),
    ]
