# Generated by Django 3.0.5 on 2020-04-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz_def',
            name='kviz_vytvoreny',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pokus',
            name='pokus_datum',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pokus',
            name='pokus_koniec',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pokus',
            name='pokus_zaciatok',
            field=models.TimeField(auto_now=True),
        ),
    ]
