# Generated by Django 3.0.5 on 2020-04-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0002_auto_20200417_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='odpoved_def',
            name='odpoved_znenie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otazka_def',
            name='otazka_znenie',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='skusanie',
            name='popis',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
