# Generated by Django 3.0.5 on 2020-04-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0003_auto_20200417_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odpoved_def',
            name='odpoved_body',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pokus',
            name='pokus_neodpovedal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pokus',
            name='pokus_neuhadol',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pokus',
            name='pokus_uhadol',
            field=models.IntegerField(),
        ),
    ]
