# Generated by Django 3.0.5 on 2020-04-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0004_auto_20200417_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='odpoved',
            name='odpoved_spravnost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='odpoved_def',
            name='odpoved_spravna',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skusanie',
            name='termin',
            field=models.DateField(auto_now=True),
        ),
    ]
