# Generated by Django 3.0.5 on 2020-04-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0005_auto_20200417_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odpoved',
            name='odpoved_moja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tiaprojekt.Odpoved_def'),
        ),
        migrations.AlterField(
            model_name='odpoved',
            name='otazka_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tiaprojekt.Otazka_def'),
        ),
    ]
