# Generated by Django 3.0.5 on 2020-04-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0006_auto_20200418_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokus',
            name='odpoved_id',
        ),
        migrations.AddField(
            model_name='odpoved',
            name='pokus_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tiaprojekt.Pokus'),
        ),
    ]
