# Generated by Django 3.0.5 on 2020-04-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0008_remove_odpoved_odpoved_spravnost'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokus',
            name='pokus_body',
            field=models.IntegerField(default=0),
        ),
    ]
