# Generated by Django 3.0.5 on 2020-04-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0007_auto_20200418_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odpoved',
            name='odpoved_spravnost',
        ),
    ]
