# Generated by Django 3.0.5 on 2020-04-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0009_pokus_pokus_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odpoved_def',
            name='otazka_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tiaprojekt.Otazka_def'),
        ),
        migrations.AlterField(
            model_name='otazka_def',
            name='kviz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tiaprojekt.Kviz_def'),
        ),
    ]
