# Generated by Django 3.0.5 on 2020-04-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0010_auto_20200420_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odpoved',
            name='pokus_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='tiaprojekt.Pokus'),
        ),
    ]
