# Generated by Django 3.0.5 on 2020-05-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0011_auto_20200420_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odpoved',
            name='odpoved_moja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiaprojekt.Odpoved_def'),
        ),
        migrations.AlterField(
            model_name='odpoved',
            name='otazka_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiaprojekt.Otazka_def'),
        ),
        migrations.AlterField(
            model_name='odpoved',
            name='pokus_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tiaprojekt.Pokus'),
        ),
        migrations.AlterField(
            model_name='odpoved_def',
            name='otazka_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiaprojekt.Otazka_def'),
        ),
        migrations.AlterField(
            model_name='otazka_def',
            name='kviz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiaprojekt.Kviz_def'),
        ),
        migrations.AlterField(
            model_name='pokus',
            name='kviz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiaprojekt.Kviz_def'),
        ),
    ]
