# Generated by Django 3.0.5 on 2020-05-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0012_auto_20200511_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kviz_def',
            name='kviz_typ',
            field=models.CharField(max_length=50),
        ),
    ]
