# Generated by Django 3.0.5 on 2020-05-15 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0013_auto_20200511_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_pswd', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='odpoved',
            name='odpoved_moja',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tiaprojekt.Odpoved_def'),
        ),
    ]
