# Generated by Django 3.0.5 on 2020-05-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0014_auto_20200516_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odpoved',
            name='odpoved_moja',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='odpoved',
            name='otazka_id',
            field=models.IntegerField(),
        ),
    ]
