# Generated by Django 3.0.5 on 2020-05-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0017_auto_20200516_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kviz_def',
            name='user',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='pokus',
            name='user',
            field=models.IntegerField(default=-1),
        ),
    ]
