# Generated by Django 3.0.5 on 2020-05-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0018_auto_20200516_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kviz_def',
            name='user',
        ),
    ]
