# Generated by Django 3.0.5 on 2020-05-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0019_remove_kviz_def_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz_def',
            name='user',
            field=models.IntegerField(default=-1),
        ),
    ]
