# Generated by Django 3.0.5 on 2020-05-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0020_kviz_def_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokus',
            old_name='pokus_body',
            new_name='pokus_body_max',
        ),
        migrations.AddField(
            model_name='pokus',
            name='pokus_body_zisk',
            field=models.IntegerField(default=0),
        ),
    ]
