# Generated by Django 3.0.5 on 2020-05-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0021_auto_20200517_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skusanie',
        ),
    ]
