# Generated by Django 3.0.5 on 2020-05-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0022_delete_skusanie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=-1)),
                ('link', models.TextField(blank=True, null=True)),
                ('show_as', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
