# Generated by Django 3.0.5 on 2020-05-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0023_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='tmpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem', models.IntegerField(default=-1)),
            ],
        ),
    ]
