# Generated by Django 3.0.5 on 2020-05-18 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0024_tmpmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokus',
            name='user',
        ),
    ]
