# Generated by Django 3.0.5 on 2020-05-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaprojekt', '0025_remove_pokus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokus',
            name='user',
            field=models.IntegerField(default=-1),
        ),
    ]
